version: "3.8"
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  cache:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redisdata:/data