version: "3.8"
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  cache:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redisdata:/data
  queue-ui:
    container_name: "astravest_tasks_ui"
    image: hibiken/asynqmon
    platform: linux/amd64
    ports:
        - "8080:8080"
    depends_on:
        - cache
    command: ["--redis-url=redis://cache:6379"]